#!/bin/sh
# Created by Ryan Boren
# Later code and patches from
# Kimmo Suominen (more) and Nikolay Bachiyski (less)

TEMPLATE=wordpress.pot
cwd=`pwd`
cd "$1" || exit 1

cp /dev/null "$cwd/$TEMPLATE"

find . -name '*.php' -print \
| sed -e 's,^\./,,' \
| sort \
| xargs xgettext \
    --keyword=__ \
    --keyword=_e \
	--keyword=__ngettext:1,2 \
    --default-domain=wordpress \
    --language=php \
    --output="$cwd/$TEMPLATE" \
    --join-existing \
	--from-code utf-8
cd "$cwd"

if [ -n "$2" ]; then
    if [ x$2 = 'x-p' ]; then
	msgfmt --statistics "$TEMPLATE"
    else
	if [ -f $2.po ]; then
	    msgmerge -o ".tmp$2.po" "$2.po" "$TEMPLATE" \
	    && mv ".tmp$2.po" "$2.po" \
	    && msgfmt --statistics -o "$2.mo" "$2.po"
	else
	    echo "Usage: $0 directoy [-p|locale]"
	fi
    fi
fi
